(defun shell-other-window()
	(interactive)
	(let ((buf (eshell)))
		(switch-to-buffer (other-buffer buf))
		(switch-to-buffer-other-window buf)))
(defun custom-eshell-ow-command()
	(interactive)
	(cond ((eq "*scratch*" (window-buffer (selected-window)))
		   (shell-other-window))
		  ((get-buffer-window "*scratch*")
		   (eshell))
		  (t (shell-other-window))))

(global-set-key (kbd "s-s") 'custom-eshell-ow-command)
(global-set-key (kbd "C-c s") 'shell)
