(custom-set-faces
 ;; '(dired-directory ((t (:foreground "#75507b"))))
 ;;  '(dired-directory ((t (:foreground "#114488"))))
 '(dired-directory ((t (:foreground "#4286f4"))))
 '(dired-symlink ((t (:foreground "#75507B"))))
 '(font-latex-sectioning-0-face ((t (:inherit variable-pitch :foreground "#bebebe" :weight bold))))
 '(font-latex-sectioning-1-face ((t (:foreground "#bebebe" :inherit font-latex-sectioning-0-face :height 0.95))))
 '(font-latex-sectioning-2-face ((t (:foreground "#bebebe" :inherit font-latex-sectioning-1-face :height 0.9))))
 '(font-latex-sectioning-3-face ((t (:foreground "#bebebe" :inherit font-latex-sectioning-2-face :height 0.85))))
 '(font-latex-sectioning-4-face ((t (:foreground "#bebebe" :inherit font-latex-sectioning-3-face :height 1.0))))
 '(font-latex-sectioning-5-face ((t (:foreground "#bebebe" :inherit font-latex-sectioning-4-face :height 1.0))))
 '(trailing-whitespace ((t (:background "#ffb6b0"))))
 '(variable-pitch ((t (:font "Sans-Serif-16"))))
;; '(vterm-color-default ((t(:inherit foreground :inherit background ))))
;; '(vterm-color-black   ((t(:inherit background :foreground "#000000"))))
;; '(vterm-color-red	   ((t(:inherit background :foreground "#cc0000"))))
;; '(vterm-color-green   ((t(:inherit background :foreground "#4E9A06"))))
;; '(vterm-color-yellow  ((t(:inherit background :foreground "#C4A000"))))
;; '(vterm-color-blue	   ((t(:inherit background :foreground "#4286f4"))))
;; '(vterm-color-magenta ((t(:inherit background :foreground "#FFC0CB"))))
;; '(vterm-color-cyan	   ((t(:inherit background :foreground "#06989A"))))
;; '(vterm-color-white   ((t(:inherit background :foreground "#D3D7CF"))))
 )
