;;; Compiled snippets and support files for `latex-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'latex-mode
		     '(("wed" "\\wedge $0" "wedge" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/wedge-and" nil nil)
		       ("vee" "\\vee $0" "or" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/vee-or" nil nil)
		       ("times" "$\\times$$0" "times" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/times" nil nil)
		       ("tfrac" "\\tfrac{$1}{$2}$0" "tfrac" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/tfrac" nil nil)
		       ("bf" "\\textbf{$0}" "textbf" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/testbf" nil nil)
		       ("tag" "\\tag{$0}" "tag" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/tag" nil nil)
		       ("table" "\\captionof{table}{}\n\\begin{tabularx}{\\textwidth}{X X X}\n\n\\label{tb}\n\\end{tabularx}\n" "table" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/table" nil nil)
		       ("subsubsec" "\\subsubsection{}" "subsubsec" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/subsubsection" nil nil)
		       ("subsec" "\\subsection{}" "subsec" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/subsection" nil nil)
		       ("subq" "\\subseteq" "subq" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/subq" nil nil)
		       ("sqr" "\\sqrt{$1} $0" "sqrt" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/sqrt" nil nil)
		       ("sec" "\\section{}" "sec" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/section" nil nil)
		       ("rref" "\\stackrel{$1}{$2} $0" "rref" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/rref" nil nil)
		       ("ra" "\\rightarrow $0" "rightarrow" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/rightarrow_math" nil nil)
		       ("rarrow" "$\\rightarrow$$0" "rarrow" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/rightarrow" nil nil)
		       ("qq" "\\qquad $0" "qquad" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/qquad" nil nil)
		       ("qed" "\\begin{flushright}\n$\\blacksquare/QED\\qquad$\n\\end{flushright}\n" "qed" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/qed" nil nil)
		       ("pmod" "\\pmod{$1} $0" "pmod" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/pmod" nil nil)
		       ("pmat" "\\begin{pmatrix}\n$0\n\\end{pmatrix}" "pmat" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/pmatrix" nil nil)
		       ("ol" "\\overline{$1}$0" "overline" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/overline" nil nil)
		       ("***" "\\subsubsection{$0}" "org-subsubsection" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/org-subsubsection" nil nil)
		       ("**" "\\subsection{$0}" "org-subsection" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/org-subsection" nil nil)
		       ("*" "\\section{$0}" "org-section" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/org-section" nil nil)
		       ("ne" "\\neg $0" "negation" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/negation" nil nil)
		       ("mti" "\\times $0" "times" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/mtimes" nil nil)
		       ("mcal" "\\mathcal{$1}$0" "mcal" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/mcal" nil nil)
		       ("mbb" "\\mathbb{$1}$0" "mathbb" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/mbb" nil nil)
		       ("mat" "\\begin{matrix}\n$0\n\\end{matrix}" "mat" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/matrix" nil nil)
		       ("txt" "\\text{ $1 } $0" "txt" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/math_text" nil nil)
		       ("sim" "\\sim $0" "sim" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/math-sim" nil nil)
		       ("lst" "\\begin{lstlisting}[frame=single]\n$0\n\\end{lstlisting}" "lst" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/lstlisting" nil nil)
		       ("log" "\\log{$0}" "log" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/log" nil nil)
		       ("literature" "\\usepackage[backend=biber, style=authoryear,\nnatbib=true,\nhyperref=true]{biblatex}\n\\addbibresource{literature.bib}" "literature" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/literature" nil nil)
		       ("itemize" "\\begin{itemize}\n \\item\n \\item\n \\item\n\\end{itemize}" "itemize" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/itemize" nil nil)
		       ("lsti" "\\lstinputlisting[language=$1,frame=single]{$0}" "importlst" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/importlst" nil nil)
		       ("img" "\\begin{center}\n	\\includegraphics[width=1.0\\textwidth]{$0}\n %	\\captionof{figure}{}\n	\\label{fig:}\n\\end{center}" "image" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/image" nil nil)
		       ("frac" "\\frac{$1}{$2}$0" "frac" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/frac" nil nil)
		       ("flushright" "\\begin{flushright}\n$0\n\\end{flushright}" "flushright" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/flushright" nil nil)
		       ("eq" "\\equiv $0" "equiv" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/equiv" nil nil)
		       ("dfrac" "\\dfrac{$1}{$2}$0" "dfrac" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/dfrac" nil nil)
		       ("cite" "(\\cite[p. $1]{$0})" "cite" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/cite" nil nil)
		       ("cd" "\\cdot $0" "dot" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/cdot" nil nil)
		       ("box" "\\begin{box}{}\n\n\\end{box}" "box" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/box" nil nil)
		       ("bgdoc" "\\documentclass[12pt,a4paper]{scrartcl}\n\n\\usepackage{amsfonts,amsmath,amssymb,amsthm}\n\\usepackage{booktabs}\n\\usepackage{caption}\n\\usepackage{capt-of}\n\\usepackage{changepage}\n\\usepackage{fullpage}\n\\usepackage[euler]{textgreek}\n\\usepackage{textcomp}\n\\usepackage{mathtools}\n\\usepackage{pmboxdraw}\n\\usepackage{listings}\n\\usepackage{marvosym}\n\\usepackage{ragged2e}\n\\usepackage{tikz}\n% \\usepackage[onehalfspacing]{setspace}\n\\usepackage{hyperref}\n\\hypersetup{\n    colorlinks=true, % make the links colored\n    linkcolor=black, % color TOC links in blue\n    urlcolor=red, % color URLs in red\n    linktoc=all, % 'all' will create links for everything in the TOC\n    citecolor=black\n}\n\n\\title{}\n\\author{}\n\\date{}\n\\setlength{\\parindent}{0pt}\n\n\\begin{document}\n\n\\end{document}" "bgdoc" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/bgdoc" nil nil)
		       ("frame" "\\begin{frame}\n\\frametitle{}\n\n\\end{frame}" "new Frame" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/begin_frame" nil nil)
		       ("bgbeamer" "\\documentclass{beamer}\n\\usepackage[utf8]{inputenc}\n\\usepackage{lmodern}\n\\usepackage[ngerman]{babel}\n\\usepackage{amsmath, capt-of,lipsum}\n\\usepackage{graphicx}\n\\usepackage{caption}\n\\usepackage{multicol}\n\\usepackage{textcomp}\n\\usepackage{wrapfig}\n\\usepackage{tabularx}\n\\usepackage[euler]{textgreek}\n\\usepackage{booktabs}\n\\usepackage{color}\n\\usepackage{subcaption}\n\\usepackage{ragged2e}\n\\usepackage[version=4]{mhchem}\n\\usepackage{enumitem}\n\\usepackage{hyperref}\n\n\n\\usetheme{Copenhagen}\n\\hypersetup{\n    colorlinks=true, % make the links colored\n    linkcolor=white, % color TOC links in blue\n    urlcolor=red, % color URLs in red\n    linktoc=all % 'all' will create links for everything in the TOC\n}\n\n\\title{}\n\\subtitle{}\n\\author{}\n\\date{}\n\n\\begin{document}\n\\frame{\\titlepage}\n\n\n\\end{document}" "Begin Beamer" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/begin_beamer" nil nil)
		       ("array" "\\[\\left . \\begin{array}\n$0\n\\end{array}\\right\\]" "array" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/array" nil nil)
		       ("align*" "\\begin{align*}\n$0\n\\end{align*}" "align no num" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/align_no_num" nil nil)
		       ("align" "\\begin{align}\n$0\n\\end{align}" "align" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/align-math" nil nil)
		       ("Ra" "\\Rightarrow $0" "Rightarrow" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/Rightarrow_double" nil nil)
		       ("Lra" "\\Longrightarrow" "Longrightarrow" nil nil nil "/home/gabriel/.emacs.d/snippets/latex-mode/Longrightarrow" nil nil)))


;;; Do not edit! File generated at Thu May 30 23:49:56 2019
